[package]
name = "pmz-common"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/wqld/pmz"
description = "Common crate for pmz"

[features]
default = []
user = ["aya"]

[dependencies]
aya = { workspace = true, optional = true }

[lib]
path = "src/lib.rs"
